---

- name: "{{ site_domain}} : Ensure {{ site_exim4_dkim_keys_path }} exists"
  file:
    path: "{{ site_exim4_dkim_keys_path }}"
    state: directory
    owner: Debian-exim
    group: Debian-exim
    mode: 0700

- name: "{{ site_domain}} : Add DKIM private key"
  template:
    src: exim4/dkim_private_key.j2
    dest: "{{ site_exim4_dkim_keys_path }}/{{ site_exim4_dkim_domain }}.key"
    owner: root
    group: Debian-exim
    mode: 0640
